apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-scalling
rules:
  - apiGroups: ["*"]
    resources:
      - pods
      - deployments
      - namespace
      - deployments/scale
      - statefulset
      - statefulsets
      - statefulsets/scale
    verbs:
      - get
      - list
      - delete
      - scale
      - patch
